# Generated by Django 5.0.4 on 2024-04-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='contact', max_length=200),
            preserve_default=False,
        ),
    ]
